---
name: 'tagged-release'

on:
  push:
    tags:
      - 'v*'

jobs:
  gh_tagged_release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Github Automatic Releases
        uses: ramonrwx/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
