---
name: 'tests'
on:
  push:
  pull_request:
    types:
      - 'opened'
      - 'closed'
      - 'reopened'
      - 'synchronize'
jobs:
  gh_tests:
    runs-on: 'ubuntu-latest'
    env:
      JEST_VERBOSE: true
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          lfs: true
          fetch-depth: 0
      - name: 'Setup node'
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16
          cache-dependency-path: 'package-lock.json'
      - name: 'Install depedencies'
        run: 'npm install'
      - name: 'Check lint'
        run: 'npm run lint'
      - name: 'Testing'
        run: 'npm test'
